language: rust
cache: cargo
rust:
    - stable
    - nightly
addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
before_script:
    - rm target/debug/rowcol-*
after_success:
    - wget https://github.com/SimonKagstrom/kcov/archive/v31.tar.gz
    - tar xzf v31.tar.gz
    - cd kcov-31 && mkdir build && cd build && cmake .. && make && cd ../..
    - ./kcov-31/build/src/kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/rowcol-*
